import type { FaqItem } from "./faq";

export interface LlmsTxtInput {
  siteName: string;
  description: string;
  queries: string[];
  faqs: FaqItem[];
}

/** Deterministic — no LLM call needed */
export function generateLlmsTxt(input: LlmsTxtInput): string {
  const { siteName, description, queries, faqs } = input;
  const date = new Date().toISOString().split("T")[0];

  const faqSection = faqs
    .map((f) => `### ${f.question}\n${f.answer}`)
    .join("\n\n");

  const topicsSection = queries.map((q) => `- ${q}`).join("\n");

  return [
    `# ${siteName}`,
    `> ${description}`,
    "",
    "## Key Topics",
    topicsSection,
    "",
    "## Frequently Asked Questions",
    faqSection,
    "",
    "## Notes",
    `- Last updated: ${date}`,
    `- Generated by Gwaihir AEO Optimizer`,
  ].join("\n");
}
